include:
  - board: nice_nano_v2
    shield: corne_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: nice_nano_v2
    shield: corne_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
